<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Registrasi extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id'          => [
                'type'           => 'INT',
                'constraint'     => 5,
                'unsigned'       => true,
                'auto_increment' => true
            ],
            'nis' => [
                'type' => 'VARCHAR',
                'constraint' => '20',
            ],
            'nama_siswa' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
            ],
            'jenis_kelamin' => [
                'type' => 'ENUM("laki-laki","perempuan")',
                'null' => true,
            ],
            'umur' => [
                'type' => 'INT',
                'constraint' => 3,
            ],
            'agama' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
            ],
            'alamat' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
            ],
            'kelas' => [
                'type' => 'VARCHAR',
                'constraint' => '10',
            ],
            'hobi' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
            ],
            'tinggi_badan' => [
                'type' => 'VARCHAR',
                'constraint' => '10',
            ],
            'berat_badan' => [
                'type' => 'VARCHAR',
                'constraint' => '10',
            ],
            'alasan_basket' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'kode_pendaftaran' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
            ],
            'created_at DATETIME DEFAULT CURRENT_TIMESTAMP'
        ]);

    $this->forge->addKey('id', true);
    $this->forge->createTable('registrasi');

    // Set kd_pendaftaran as auto-generated by concatenating the first 3 letters of nama_siswa, 2 digits of umur, and the last digit of the generated id.
    // $this->db->query('ALTER TABLE `registrasi` MODIFY `kd_pendaftaran` VARCHAR(15) AS (CONCAT("daftar-", LPAD(`id`, 2, "0"))))');
    }

    public function down()
    {
        $this->forge->dropTable('registrasi');
    }
}
